_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

login:
    path: /login
    controller: App\Controller\AccountController::login
    methods: [GET, POST]

register:
    path: /register
    controller: App\Controller\AccountController::register
    methods: [GET, POST]

logout:
    path: /logout
    controller: App\Controller\AccountController::logout
    methods: [GET, POST]

resetPassword:
    path: /resetPassword
    controller: App\Controller\AccountController::sendPasswordResetEmail
    methods: [GET, POST]

setNewPassword:
    path: /setNewPassword/{token}
    controller: App\Controller\AccountController::showResetPasswordTemplate
    methods: [GET, POST]

setNewUserPassword:
    path: /setNewUserPassword/{email}
    controller: App\Controller\AccountController::setNewUserPassword
    methods: [GET, POST]

changeLanguage:
    path: /changeLang/{lang}
    controller: App\Controller\LanguageController::changeLanguage
    methods: [GET, POST]

updateProfile:
    path: /updateProfile
    controller: App\Controller\AccountController::updateProfile
    methods: [GET, POST]

onepager:
    path: /onepager
    controller: App\Controller\OnePagerController::defaultAction
